server:
  port: 8087
spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
zuul:
  routes:
    service-a:
      #设置服务a路径名称，随便起(服务的别名路径)
      path: /service-a/**
      #这里写a服务的注册名字
      serviceId: service-objcat-a
    service-b:
      path: /service-b/**
      serviceId: service-objcat-b
